### ISSUE TITLE
Microsoft Azure active directory support

### ISSUE THREAD

**Issue by aidesigner** [paulvanbladel/aurelia-auth#10]
First thanks for this resource as it is very well put together.  I am learning Aurelia to build a website that will be located on Azure, which I imagine will be very common.  Azure has a strong and well support authentication solution, which is Azure active directory. I am learn about this token based solution and provided some links below.

Is it practical and would you consider adding support for Azure active directory to aurelia-auth.  Azure active directory provides solutions for Auth 2.0 Facebook/Yahoo, so I don't understand if there is an overlap.

http://blogs.msdn.com/b/brunoterkaly/archive/2014/03/03/introduction-to-windows-azure-active-directory.aspx
http://www.andrewconnell.com/azure-ad-asp-net-mvc-walk-through-implementing-adal-owin
http://justazure.com/azure-active-directory-part-1-introduction/

Thanks again...

**Comment by paulvanbladel** [comment]
My solution is pure oauth (and local login).
In my understanding, azure active directory could be interesting when there is a need for a more federated solution (so integrating windows identities that lives 'on premise').
I never used azure AD, but my solution is backend agnostic, whereas azure AD, well ... that's azure, so you select a particular vendor.

**Comment by aidesigner** [comment]
Thank you for the clarification, perhaps I will try both solutions and compare.  To compare, in your solution the user can choose to authenticate with google and then next time with twitter.  In this case do I fetch information with the token from google/twitter to realize it is the same user?

**Comment by paulvanbladel** [comment]
Accounts can be linked together, or associated if you want.

**Comment by aidesigner** [comment]
I understand, and let me conclude with a question on features as compared to Azure Active Directory (AAD).
-aurelia-auth concludes by providing a token which can optionally be linked to other tokens?
-If I wish to store user data (ie. User phone number) I should then use the token as a key to a custom backend dababase?
-Some feature unique to AAD are "on premise" federation (Not interested) and Single-Sign-On (Maybe interested).  The Single-Sign-On concept should be build on top of aurelia-auth or perhaps not really relevant to a website?

**Comment by paulvanbladel** [comment]
Well, the app (the server part, check the nodeJs sample app) still manages it users, but it does not manage Identities (read: password) except for the local strategy, for all other oauth based providers, the actual authentication is done by google/facebook/twitter, ...
When a user is created server side, other (not yet taken) identities can be linked to that user.
Indeed, single sign on (under the assumption, you mean a windows identity) can achieve probably with AAD.

**Comment by aidesigner** [comment]
I should have mentioned I have a VS 2015 ASP.NET 5 project (No nodejs) that simple delivers the aurelia SPA files.  Perhaps your server managed comments still apply, but I will have to learn.  So given my setup where and how would I store the users phone number (ie. Use aurelia-auth token to access database)?

**Comment by paulvanbladel** [comment]
should be part of the user profile table, basically it's of the same order as user display name.

**Comment by aidesigner** [comment]
Thanks for your insight.  What I am after is actually lots of custom data per user (Beyond profile) like products they bought or whatever.  Just making sure I understand where I might put/access this data with your solution.  Since your authentication revolves around a unique token per user, do  you agree it makes since to use the token as the key to into my custom backend database to hold user information?

**Comment by paulvanbladel** [comment]
Not a good idea,   token is created when you sign in.  User must have unique id.

**Comment by aidesigner** [comment]
Yes I will stick a unique id placed in the profile table I obtain from the provider (yahoo, google, ...).  Then create a backend ASP.NET Web API2 database to hold tons of user info, which is indexed by the unique ID.

I think your solution is well done, stands out, and probably suites almost everyone.  I remain on the fence because I am heavily committed to the Microsoft Azure infrastructure.  Maybe I can somehow take advantage of AAD single-sign-on in the future.  Also for a paid service they have some features like multi-factor authentication.

Feel free to closed the ticket if you see fit, and again thanks for the help.

**Comment by paulvanbladel** [comment]
Indeed, the current implementation is quite generic.
I suggest you further explore AAD and that you come back if you see further opportunitities to refine aurelia-auth.
thanks for the support
paul.
