### ISSUE TITLE
Aurelia Router breaks after aurelia-auth installation

### ISSUE THREAD

**Issue by simeonoff** [paulvanbladel/aurelia-auth#100]
I get the following immediately after I do jspm install aurelia-auth:
```
ERROR [app-router] Error: Route loaders must implement "loadRoute(router, config, navigationInstruction)".
ERROR [app-router] Router navigation failed, and no previous location could be restored.
```
This is on a new aurelia-skeleton(latest build), so everything is as is. Am I doing something wrong?

**Comment by simeonoff** [comment]
You can close the issue, turns out I had to run the 

> jspm install aurelia-auth --lock

to prevent the installer from doing overrides of the local packages.

**Comment by jasonhjohnson** [comment]
I'm getting this issue too. Tried uninstalling aurelia-auth and running `jspm install aurelia-auth --lock` with no luck.

**Comment by paulvanbladel** [comment]
Try cleaning map section in config.Js and run jspm install.
Aurelia Auth sample seems to work fine

**Comment by jasonhjohnson** [comment]
@paulvanbladel  That did the trick. Thanks.
