### ISSUE TITLE
decomposeToken is not defined in chrome console

### ISSUE THREAD

**Issue by Ma3yTa** [paulvanbladel/aurelia-auth#102]
Steps to reproduce:
1) login
2) reload page
[config.txt](https://github.com/paulvanbladel/aurelia-auth/files/154363/config.txt)

I think it releated to new aurelia update http://blog.durandal.io/2016/03/01/aurelia-early-march-2016-update/

**Comment by Exsilium122** [comment]
https://github.com/Exsilium122/aurelia-auth/commit/1f7fa2d9311c4a3ef2ef8ed9e401c1531a70b80f
Does this commit fix your problems?

**Comment by Ma3yTa** [comment]
Yes. It fixed. 
Thanks

**Comment by paulvanbladel** [comment]
@Exsilium122 thanks, i found the bug in the mean time and pushed new tag v0.12.13.
