### ISSUE TITLE
Accept headers for login are incorrect on Firefox

### ISSUE THREAD

**Issue by txels** [paulvanbladel/aurelia-auth#11]
I just started using aurelia-auth (great library!) to authenticate against my own service using JWT.

I managed to make it work using https://github.com/paulvanbladel/aurelia-auth-sample as a base and modifying `authConfig.js` to meet my needs:

```js
var configForDevelopment = {
	providers: {
            ...
	},
    baseUrl: 'http://localhost:7001/',
    loginUrl: '/api-token-auth/',
    loginRedirect: '/#/',
    profileUrl: '/accounts/me',
    authToken: 'JWT'
};
```

This works fine on Chrome but not on Firefox. I found the reason for it to be that on Chrome login sends `Accept: */*` whereas on Firefox it sends `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`. My backend honors HTTP content negotiation and sends back HTML, but your `authService` assumes it gets JSON back.

I suggest that `authService` should configure HttpService to send an accept header of `application/json`, if you expect the response to come in that format (probably in https://github.com/paulvanbladel/aurelia-auth/blob/master/src/authService.js#L62 unless it can be better set globally).

**Comment by txels** [comment]
(I could try and write a PR, with some guidance as to where to best do this)

**Comment by paulvanbladel** [comment]
Hi, would be great to make a PR because I leave on holiday now.
Don't worry too much about PR format, I have no problem with integrating the code if you even drop it here in a comment.
thanks
paul.
