### ISSUE TITLE
package install error with latest version 0.13.1

### ISSUE THREAD

**Issue by soarer25** [paulvanbladel/aurelia-auth#110]
Hi, 

I'm getting an error during install with the latest version of the package. I was trying this with the latest Aurelia skeleton (beta1.2.0). Yesterday I had successfully added the aurelia-auth package to a project. This only happened today, I guess with the latest version?

Any ideas what the cause might be ?

The output from the jspm install is

C:\Aurelia\skeleton-navigation-1.0.0-beta.1.2.0\skeleton-es2016>jspm install aurelia-auth
     Updating registry cache...
     Looking up github:paulvanbladel/aurelia-auth
     Downloading github:paulvanbladel/aurelia-auth@0.13.1

warn Error on processPackageConfig
     Package.json dependency aurelia-dependency-injection set to npm:aurelia-dependency-injection@^1.0.0-beta.1.1.4, which is not a valid dependency format for npm.
     It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.

_err  Error: Error processing package config for github:paulvanbladel/aurelia-auth.
         at C:\Aurelia\skeleton-navigation-1.0.0-beta.1.2.0\skeleton-es2016\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:27:9
         at Object.lib$rsvp$events$$default.trigger (C:\Aurelia\skeleton-navigation-1.0.0-beta.1.2.0\skeleton-es2016\node_modules\rsvp\dist\rsvp.js:245:13)
         at null._onTimeout (C:\Aurelia\skeleton-navigation-1.0.0-beta.1.2.0\skeleton-es2016\node_modules\rsvp\dist\rsvp.js:568:47)
         at Timer.listOnTimeout (timers.js:92:15)

err  Error processing package config for github:paulvanbladel/aurelia-auth.

warn Installation changes not saved.

C:\Aurelia\skeleton-navigation-1.0.0-beta.1.2.0\skeleton-es2016>

Thanks for your help 
    Garrett

**Comment by paulvanbladel** [comment]
sorry for the trouble.
try v0.13.6 (latest).
cheers
paul.

**Comment by soarer25** [comment]
Great stuff - thanks a million for that - (great package by the way)
