### ISSUE TITLE
Error on install via jspm

### ISSUE THREAD

**Issue by dautushenka** [paulvanbladel/aurelia-auth#111]
> jspm install aurelia-auth
>      Creating registry cache...
>      Looking up github:paulvanbladel/aurelia-auth
>      Downloading github:paulvanbladel/aurelia-auth@0.13.1
> 
> warn Error on processPackageConfig
>      Package.json dependency aurelia-dependency-injection set to npm:aurelia-dependency-injection@^1.0.0-beta.1.1.4, which is not a valid dependency format for npm.
>      It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.
> 
> err  Error: Error processing package config for github:paulvanbladel/aurelia-auth.
>          at /home/dautushenka/Go/src/tulacoby/front-end/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:27:9
>          at Object.lib$rsvp$events$$default.trigger (/home/dautushenka/Go/src/tulacoby/front-end/node_modules/rsvp/dist/rsvp.js:245:13)
>          at null._onTimeout (/home/dautushenka/Go/src/tulacoby/front-end/node_modules/rsvp/dist/rsvp.js:568:47)
>          at tryOnTimeout (timers.js:224:11)
>          at Timer.listOnTimeout (timers.js:198:5)
> 
> err  Error processing package config for github:paulvanbladel/aurelia-auth.
>

**Comment by paulvanbladel** [comment]
should be solved in v0.13.6. Can you verify please?
