### ISSUE TITLE
Changelog is wrong

### ISSUE THREAD

**Issue by johnraz** [paulvanbladel/aurelia-auth#112]
Hi there,

Am I missing something or the [changelog](https://github.com/paulvanbladel/aurelia-auth/blob/master/doc/CHANGELOG.md) is wrong?

**Comment by paulvanbladel** [comment]
sorry, should give more attentions to these details :(

**Comment by johnraz** [comment]
No problem at all, I was just wondering and figured I should let you know ;-)

**Comment by paulvanbladel** [comment]
yeah, I should check how this works, no doubt it's easy :)

**Comment by johnraz** [comment]
Yep, I would have kept the issue open though until it is resolved, for further reference for others that may be wondering ;-

**Comment by paulvanbladel** [comment]
feel free to submit PR of course :)

**Comment by RWOverdijk** [comment]
@paulvanbladel `gulp prepare-release`

https://github.com/paulvanbladel/aurelia-auth/blob/master/build/tasks/prepare-release.js#L15

You have to change your commit style though: https://github.com/SpoonX/about/blob/master/CONTRIBUTING.md#commit

To see how that works you can check out ours: https://github.com/SpoonX/aurelia-authentication

**Comment by paulvanbladel** [comment]
@johnraz . gulp-conventional-changelog works better.
I'll adopt the commit message conventions and we'll get **from now on** better change logs.
Thanks for bringing it to my attention.

**Comment by johnraz** [comment]
No problem thanks for looking into it.
