### ISSUE TITLE
Asp.net Web Api 2

### ISSUE THREAD

**Issue by sethom** [paulvanbladel/aurelia-auth#118]
I understand that aurelia-auth is a port of Satellizer. Does this mean I can assume that if Satellizer supports a feature, aurelia-auth does as well? Specifically I'm interested in the Asp.net Web Api 2 compatibility that was added to Satellizer in May 2015 (https://github.com/sahat/satellizer/issues/219) and whether this has made it over to aurelia-auth as well.

Thanks!

**Comment by paulvanbladel** [comment]
I'm using web api here with aurelia-auth:
https://github.com/paulvanbladel/aurelia-identityserver-aspnetcore

**Comment by sethom** [comment]
Thanks Paul. When I build the solution in Visual Studio it's giving me the error that "The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters." when doing "Building directory '/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-computed-properties/node_modules/babel-helper-define-map/node_modules/babel-helper-function-name/node_modules/babel-traverse/lib/'
It even does this when I move the solution folders directly to c:\  ..   

How are you building this on Windows which such long paths?

**Comment by paulvanbladel** [comment]
Yeah, for me, reasons to buy a mac☺
When i Download in a short root folder  it  works.

**Comment by sethom** [comment]
Ah! Oh how I wish I got to use my iMac for my work. My company forces me to use Windows though. Maybe with all the new cross platform stuff like Xamarin becoming more affordable he'll eventually let me switch.

I'm seeing some fixes though for the long path issue. I'll give those a try.  Thanks for all your hard work on your aurelia plugin!

**Comment by paulvanbladel** [comment]
Thanks!
Maybe your version of npm is not recent enough?

**Comment by Vidarls** [comment]
Update to node 5.x and you'll get npm 3.x which uses a flat dependency structure, no more deep nestings.

Just delete your modules folders and re-run npm install / jspm install and you should be good to go (i think)

**Comment by paulvanbladel** [comment]
Thanks @Vidarls  for being more precise than I was.
@sethom that fixed the problem for you?

**Comment by sethom** [comment]
Thanks, the node 5.x upgrade works fine. Thanks for the help!
