### ISSUE TITLE
Error: inject is not a function

### ISSUE THREAD

**Issue by vincenzoraco** [paulvanbladel/aurelia-auth#13]
I followed the tutorial to install the plugin but when I add this:

```
.plugin('paulvanbladel/aurelia-auth', (baseConfig)=>{
         baseConfig.configure(config);
    });
```

and/or this:

```
import {AuthService} from 'paulvanbladel/aurelia-auth';
import {inject} from 'aurelia-framework';
@inject(AuthService)
```

I get the error ``` Error: inject is not a function ``` . When I call the plugin there is a problem on:

```
/* storage.js file, line 98 */
Storage = inject(BaseConfig)(Storage) || Storage;
```

or on any file that call the inject function. I tried to clear the jspm cache and install all the dependencies again, but it does not solve the problem.

Is an aurelia-auth problem, mine or aurelia-framework?

Thanks for any help

**Comment by maxfrigge** [comment]
I am having the same issue.

**Comment by paulvanbladel** [comment]
@vincenzoraco @maxfrigge .
yeah, is due to aurelia framework updates.
Working on it right now. Keep you posted.
cheers
paul.

**Comment by paulvanbladel** [comment]
There was a breaking change in aurelia-framework: aurelia.globalizeResources is renamed to aurelia.globalResources.
The corresponding sample app (aurelia-auth-sample) has been updated as well.

**Comment by chrisjasp** [comment]
I am still receiving this error despite having the latest.

**Comment by maxfrigge** [comment]
Works for me..

**Comment by chrisjasp** [comment]
Must be missing something else. I am having the same symptoms as the original post.

**Comment by maxfrigge** [comment]
Which Versions auf aurelia and aurelia-auth are you using.. do you maybe load an old bundle instead of the new source files?

**Comment by lukeskinner** [comment]
Based on the comment earlier which says 'aurelia.globalizeResources is renamed to aurelia.globalResources.', I can see a commit in aurelia-auth which changed this in the [index.js](https://github.com/paulvanbladel/aurelia-auth/commit/3e9ac8658dd2edfe6a1aedf4f16510f94c26d9b0) file.

I would recommend running ```jspm update``` which will update everything (aurelia framework + aurelia-auth and anything else you use jspm for) or just ```jspm update github:paulvanbladel/aurelia-auth``` which will update aurelia-auth.

**Comment by chrisjasp** [comment]
Sorry for the bother. I'm new to jspm. That seems to have been the issue. Thanks!

**Comment by paulvanbladel** [comment]
No worries, learning jspm can be an adventure :)
