### ISSUE TITLE
AuthService.signup(...) seems overly restrictive

### ISSUE THREAD

**Issue by fedoranimus** [paulvanbladel/aurelia-auth#132]
It seems odd to me that `AuthService.signup(displayName, email, password)` has such restrictive parameters.

Is there a strong reason behind this? Are these parameters easily customizable?

**Comment by paulvanbladel** [comment]
Yeah, the signup method is just there for making the picture complete, but signup is not part of oauth/openidconnect. So, there is few add value. Simply provide your own version of signup matching your server side needs. The real added value of aurelia-auth is in the oauth processing, token exchange and stuff like that.
Note that when your first param in the signup method is an object, you have full degrees of freedom.
