### ISSUE TITLE
Which configuration setting is the equivalent to "Tenant"?

### ISSUE THREAD

**Issue by ajdisalvo72** [paulvanbladel/aurelia-auth#133]
I would like to use this plugin to work with azure AD, which is Microsoft's Azure implementation of Oauth 2.
An example configuration  for adal.js, microsoft's javascript API is:
    window.config = {
        instance: 'https://login.microsoftonline.com/',
        tenant: '[somethingunique].onmicrosoft.com',
        clientId: 'sdfdsfdffdsdsffsdfdsfdsds',
        postLogoutRedirectUri: window.location.origin,
        cacheLocation: 'localStorage', // enable this for IE, as sessionStorage does not work for localhost.
    };

I am looking at your example config file and not seeing anything equivalent.

Can you help?

Thanks

Tony

**Comment by paulvanbladel** [comment]
I'm pretty sure microsoft follows the oauth standard correctly, so it should be a variation on the set of example providers in aurelia-auth.
Unfortunately I don't have (any longer) an azure account, so I can't test anything.
Feel free to provide PR when you have a working config for azure.
cheers
paul.
