### ISSUE TITLE
Bundle

### ISSUE THREAD

**Issue by johntom** [paulvanbladel/aurelia-auth#134]
Hi Paul,
I was having an issue bundling aurelia-auth into the final course-ware project from  aurelia fundamentals https://app.pluralsight.com/ so I deciided to test with https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext and found similar issues  After jspm install aurelia-auth and adding   "aurelia-auth" to bundles.js I get error (*1)below when doing an gulp serve-bundle. Un-installing aurial-auth does not fix. Deleting the jspm direcotry and doing jspm install produces (*2) erorr. At the moment a full reinstall is required.
TIA
John
*1------
[11:25:05] Starting 'bundle'...
[11:25:06] 'bundle' errored after 440 ms
[11:25:06] Error on fetch for npm:aurelia-logging@1.0.0-beta.2.0.0/aurelia-logging.js at file:///C:/Aurelia/skeleton-navigation/skeleton-esnext/jspm_packages/npm/aurelia-logging@1.0.0-beta.2.0.0/aurelia-logging.js
        Loading npm:aurelia-logging@1.0.0-beta.2.0.0.js
        Loading npm:aurelia-event-aggregator@1.0.0-beta.1.2.1/aurelia-event-aggregator.js
        Loading npm:aurelia-event-aggregator@1.0.0-beta.1.2.1.js
        Loading npm:aurelia-auth@3.0.1/auth-service.js
        Loading npm:aurelia-auth@3.0.1/aurelia-auth.js
        Loading npm:aurelia-auth@3.0.1.js
        Error: ENOENT: no such file or directory, open 'C:\Aurelia\skeleton-navigation\skeleton-esnext\jspm_packages\npm\aurelia-logging@1.0.0-beta.2.0.0\aurelia-logging.js'
    at Error (native)
*2------
aurelia.js:15 Uncaught (in promise) Error: History must implement activate().
    at b (http://localhost:9000/dist/aurelia.js:15:18204)
    at a.History.a.activate (http://localhost:9000/dist/aurelia.js:15:18373)
    at b.a.AppRouter.b.activate (http://localhost:9000/dist/aurelia.js:16:14286)

**Comment by paulvanbladel** [comment]
Are you using the latest aurelia auth bits because the error History must implement activate(), was corrected in last release.

**Comment by johntom** [comment]
Not sure wat I'm missing. 
I did a jspm install aurelia-auth 
This installs to C:\Aurelia\skeleton-navigation\skeleton-esnext\jspm_packages\npm\aurelia-auth@3.0.1. 
config.js has map: {
    "aurelia-animator-css": "npm:aurelia-animator-css@1.0.0-beta.1.2.1",
    "aurelia-auth": "npm:aurelia-auth@3.0.1",
...
  "npm:aurelia-auth@3.0.1": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.2.0.1",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.2.1",
      "aurelia-fetch-client": "npm:aurelia-fetch-client@1.0.0-beta.2.0.0",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.4"
    },

**Comment by briannoyes** [comment]
My sample code is all based on the Aurelia libraries at the point in time where I finalized them for production. If you are adding in new modules, they likely depend on newer versions of the aurelia modules than what was in my course exercise files. 

I think all you need to do to fix this is update the modules to the project so it grabs the latest ones using:
jspm update

**Comment by johntom** [comment]
Thanks, running jspm update after installng aurelia-auth on skellton fixes problem for skelleton

**Comment by paulvanbladel** [comment]
Thanks @briannoyes  for the help.
