### ISSUE TITLE
Overridden loginRoute is not used when checking if a user is logged in

### ISSUE THREAD

**Issue by lukeskinner** [paulvanbladel/aurelia-auth#14]
When changing the default config for the login route from ```/login``` to ```/signin```, I noticed the AuthorizeStep will always redirect to ```login``` instead of using the value in the config.

The issue seems to be a hard coded ```'login'``` in the code. Instead it should use the config to get the login redirect route. 
 https://github.com/paulvanbladel/aurelia-auth/blob/master/src/authorizeStep.js
```
 if (!isLoggedIn) {
        return next.cancel(new Redirect('login'));
      }
```

For now I've just changed my sign in page route to be 'login' which works around this.

**Comment by paulvanbladel** [comment]
Luke,
Thanks for reporting this issue.
I think I solved it.
Can you use version 0.9.10 and verify if all works as expected for you.
Cheers and thanks again for making aurelia-auth better.
paul.

**Comment by lukeskinner** [comment]
Using ```loginRoute: '/signin'``` now works as expected using version 0.9.10.
Thanks for fixing this - really enjoying using aurelia-auth so far!
