### ISSUE TITLE
"Cannot read property 'message' of null" error when a login fails

### ISSUE THREAD

**Issue by lukeskinner** [paulvanbladel/aurelia-auth#15]
I'm using the following code to login: 
```
import {AuthService} from 'aurelia-auth';
import {inject} from 'aurelia-framework';
@inject(AuthService)
export class Signin {

    constructor(auth){
        this.auth = auth;
    };

  username='';
  password='';

  login(){
      return this.auth.login(this.username, this.password)
      .then(response=>{
          console.log("success");
      })
      .catch(err=>{
          console.log("login failure");
      });
  };
}
```

When the login fails (incorrect email/password) I return a 401 Unauthorized response with the response body being an error message. In this scenario I would expect the ```err``` in the catch above to be the response from the server.

Instead I'm seeing this:
![error2](https://cloud.githubusercontent.com/assets/7475696/9424574/c4c0fa30-48e8-11e5-9e77-b7415f48b9ae.png)

Looking into the code I can see [authService.js](https://github.com/paulvanbladel/aurelia-auth/blob/master/src/authService.js) has a console.log statement when it catches an error during login which assumes ```err.content.message``` is populated. As this is null on my response it throws a new error instead of the actual server response error.

The fix for this will be to either check if ```err.content``` is defined or remove the console.log line (if someone wants to log this to the console they can add the code in their viewmodel).

![error](https://cloud.githubusercontent.com/assets/7475696/9424567/891bf174-48e8-11e5-999f-bb09241eb235.png)

**Comment by paulvanbladel** [comment]
HI Luke,
Thanks a lot for reporting the issue.
I think the authService should simply not contain any catch blocks. It's not because there is no catch block that the consumer of the authService will not be able to catch the error.
So, I removed all catch blocks and will soon update the sources and create a new version tag. I'll let you know when the new version is available.

Good "catch" :)
Thanks
paul.

**Comment by lukeskinner** [comment]
This is no longer an issue in v0.9.10. Thanks again for fixing it so quickly.

**Comment by paulvanbladel** [comment]
My pleasure.
