### ISSUE TITLE
Authentification header added only if request url is same as application host

### ISSUE THREAD

**Issue by jakubkorczyk** [paulvanbladel/aurelia-auth#159]
I have following probblem. The application is set similar to this from egzample, sadly it adds authorization header only if request url in same domain as appliction:
![image](https://cloud.githubusercontent.com/assets/12918498/18993817/5983e878-8725-11e6-8012-8503b5f8663a.png)
![image](https://cloud.githubusercontent.com/assets/12918498/18993870/a1f3cad8-8725-11e6-923d-dda11df93338.png)

**Comment by giuliogatto** [comment]
Same problem here.

**Comment by ShawnTalbert** [comment]
This sounds like expected behavior due to same-origin policy?

**Comment by jakubkorczyk** [comment]
Thanks giuliogatto. That worked for me. CORS was allowed, but 'Access-Control-Allow-Headers' was not set properly.
