### ISSUE TITLE
Update FB api version from 2.3 to latest

### ISSUE THREAD

**Issue by stephenstroud** [paulvanbladel/aurelia-auth#175]
Any plans on updating the 2.2v as it will be retied on the July 8, 2017

https://developers.facebook.com/docs/apps/changelog

**Comment by paulvanbladel** [comment]
Happy to merge a PR.

**Comment by RWOverdijk** [comment]
@stephenstroud Isn't it just part of the docs? I don't think it matters as long as you configure your providers correctly.

**Comment by stephenstroud** [comment]
@RWOverdijk  Yes as you can configure the setting. Here:
 https://github.com/paulvanbladel/aurelia-auth/blob/41b5504fc0aea19ff6f1737a9d880106cea1a5cc/dist/es2015/base-config.js#L87

however, updating it means the default configuration won't be outdated when the API retires, especially helpful for new users etc.

**Comment by stephenstroud** [comment]
@paulvanbladel  Okay thanks
