### ISSUE TITLE
converting from oidc-client

### ISSUE THREAD

**Issue by stuartbloom** [paulvanbladel/aurelia-auth#177]
Hi there

I am using IdentityServer3 and the oidc-client code to do my authentication, but would like to strip it out to use something that is designed to do the job, rather than have all the code in my view models.

I have downloaded the sample and it looks nice, and I am hoping to implement it in my application.

I have two issues:

The first is that, although there is an Authorize addPipelineStep in tjhe router, is it possible to redirect the application to the login screen (not in a popup) if authorization is required?

Secondly, the logout seems not to do anything; when I click login, I am already logged in.  Am I doing anything wrong?

Here is my config:

```
identSrv : {
	name: 'identSrv',
	url: 'https://localhost:44318/',
	authorizationEndpoint: 'https://localhost:44318/identity/connect/authorize',
	redirectUri: window.location.origin || window.location.protocol + '//' + window.location.host,
	scope: ['pv', 'openid'],
	
	responseType :'id_token token',


	scopePrefix: '',
	scopeDelimiter: ' ',
	requiredUrlParams: ['scope', 'nonce'],
	optionalUrlParams: ['display', 'state'],
	display: 'popup',
	type: '2.0',
	clientId: 'pvPortal',
	
	popupOptions: { width: 452, height: 633 }
}
```
Thanks in advance

**Comment by paulvanbladel** [comment]
Did you check: https://github.com/paulvanbladel/aurelia-identityserver-aspnetcore

**Comment by stuartbloom** [comment]
@paulvanbladel no, but I will take a look, thanks :)
