### ISSUE TITLE
Fails to process post request from Google - after now using latest version of Aurelia Webpack Babel Skeleton

### ISSUE THREAD

**Issue by JoshuaVSherman** [paulvanbladel/aurelia-auth#178]
please reference these two open issues:

https://github.com/WebJamApps/combined-front/issues/153

https://github.com/aurelia/skeleton-navigation/issues/805

Current behavior:
Intermittent freeze to the /dashboard route after login. I am using the Aurelia-Auth plugin
There was no issue before I upgraded to the latest version of this skeleton, and there is no way to debug this issue that I am aware of. Myself and another developer have tried everything we could think of for the past day, but were unsuccessful in resolving this bug. i am open to using a different plugin or front end package for auth if that is the only solution.

Expected/desired behavior:
After login, the user gets routed to the /dashboard successfully without any freeze-ups

link to repo:
https://github.com/WebJamApps/combined-front/tree/dev/src

**Comment by JoshuaVSherman** [comment]
could this be an issue with using the aurelia-webpack-plugin
and how we needed to do this in the main.js
**aurelia.use.plugin(PLATFORM.moduleName('aurelia-auth/auth-filter'));
aurelia.use.plugin(PLATFORM.moduleName('aurelia-auth'), (baseConfig)=>{
baseConfig.configure(config);
});**

**Comment by JoshuaVSherman** [comment]
This just happened from production, so it is definitely not the webpack dev server
https://www.web-jam.com/dashboard

please provide any recommendations

**Comment by paulvanbladel** [comment]
Sorry Joshua no idea. Aurelia-auth didn't change recently.

**Comment by JoshuaVSherman** [comment]
This is probably the reason, found it while looking at aurelia-authentication plug in
https://github.com/SpoonX/aurelia-authentication/issues/347

**Comment by JoshuaVSherman** [comment]
I am not currently able to reproduce the issue after I put this into the webpack config

  plugins: [
    new AureliaPlugin(),
    new ModuleDependenciesPlugin({
      'aurelia-auth': ['./auth-filter'],
      'aurelia-polymer': ['./au-select-custom-attribute'],
      'au-table': ['./au-table', './au-table-select', './au-table-sort']
    }),

@jods4
says that is is your aurelia-auth plugin and not the webpack aurelia plugin, but there was no issue until I upgraded to the newer skeleton project. He also said that it doesn't matter if we aurelia.use the plugin in the main.js or if we put it into the webpack config, it should do the same thing, but I never needed to put aurelia-auth/auth-filter in the main.js before to get it to build?
Right now, I have this in the webpack config

**Comment by JoshuaVSherman** [comment]
I have not been able to repeat this, since I moved the submodule dependancy into the webpack config
