### ISSUE TITLE
Unhandled promise rejection Error: inject is not a function

### ISSUE THREAD

**Issue by eaidland** [paulvanbladel/aurelia-auth#18]
![image](https://cloud.githubusercontent.com/assets/10772259/9732032/e8cba264-5620-11e5-8749-a31a849a036a.png)

**Comment by paulvanbladel** [comment]
You probably don't have the latest version of the aurelia framework.
See also #13.

**Comment by eaidland** [comment]
Currently using aurelia-auth@0.9.11.js

**Comment by paulvanbladel** [comment]
Yeah that's great, but I'm referring to the latest version of aurelia framework.
Take the latest skeleton-navigation and add aurelia-auth and check if that works.

**Comment by eaidland** [comment]
![image](https://cloud.githubusercontent.com/assets/10772259/9732566/1239e8d2-5625-11e5-9232-e5506f540b78.png)

Downloaded the New skeleton-navigation. Added aurelia-auth and followed the instructions.
npm install
jspm install
gulp watch

config.js
 "paulvanbladel/aurelia-auth": "github:paulvanbladel/aurelia-auth@0.9.11",

package.json
  "jspm": {
    "dependencies": {
      "aurelia-animator-css": "github:aurelia/animator-css@^0.16.0",
      "aurelia-binding": "github:aurelia/binding@^0.9.0",
      "aurelia-bootstrapper": "github:aurelia/bootstrapper@^0.17.0",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@^0.10.0",
      "aurelia-event-aggregator": "github:aurelia/event-aggregator@^0.8.0",
      "aurelia-fetch-client": "github:aurelia/fetch-client@^0.2.0",
      "aurelia-framework": "github:aurelia/framework@^0.16.0",
      "aurelia-history": "github:aurelia/history@^0.7.0",
      "aurelia-history-browser": "github:aurelia/history-browser@^0.8.0",
      "aurelia-loader": "github:aurelia/loader@^0.9.0",
      "aurelia-loader-default": "github:aurelia/loader-default@^0.10.0",
      "aurelia-logging": "github:aurelia/logging@^0.7.0",
      "aurelia-metadata": "github:aurelia/metadata@^0.8.0",
      "aurelia-path": "github:aurelia/path@^0.9.0",
      "aurelia-route-recognizer": "github:aurelia/route-recognizer@^0.7.0",
      "aurelia-router": "github:aurelia/router@^0.12.0",
      "aurelia-task-queue": "github:aurelia/task-queue@^0.7.0",
      "aurelia-templating": "github:aurelia/templating@^0.15.0",
      "aurelia-templating-binding": "github:aurelia/templating-binding@^0.15.0",
      "aurelia-templating-resources": "github:aurelia/templating-resources@^0.15.0",
      "aurelia-templating-router": "github:aurelia/templating-router@^0.16.0",
      "bootstrap": "github:twbs/bootstrap@^3.3.4",
      "core-js": "npm:core-js@^0.9.4",
      "fetch": "github:github/fetch@^0.9.0",
      "font-awesome": "npm:font-awesome@^4.3.0",
      "paulvanbladel/aurelia-auth": "github:paulvanbladel/aurelia-auth@^0.9.11"
    },

**Comment by paulvanbladel** [comment]
Strange.
Can you be so kind and switch to aurelia-auth version 0.9.10 and see if that makes a difference ?

**Comment by eaidland** [comment]
![image](https://cloud.githubusercontent.com/assets/10772259/9732912/ca656876-5627-11e5-8d9a-fddf1dfe4e88.png)

jspm install github:paulvanbladel/aurelia-auth@0.9.10

package.js:
  "jspm": {
    "dependencies": {
      "aurelia-animator-css": "github:aurelia/animator-css@^0.16.0",
      "aurelia-binding": "github:aurelia/binding@^0.9.0",
      "aurelia-bootstrapper": "github:aurelia/bootstrapper@^0.17.0",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@^0.10.0",
      "aurelia-event-aggregator": "github:aurelia/event-aggregator@^0.8.0",
      "aurelia-fetch-client": "github:aurelia/fetch-client@^0.2.0",
      "aurelia-framework": "github:aurelia/framework@^0.16.0",
      "aurelia-history": "github:aurelia/history@^0.7.0",
      "aurelia-history-browser": "github:aurelia/history-browser@^0.8.0",
      "aurelia-loader": "github:aurelia/loader@^0.9.0",
      "aurelia-loader-default": "github:aurelia/loader-default@^0.10.0",
      "aurelia-logging": "github:aurelia/logging@^0.7.0",
      "aurelia-metadata": "github:aurelia/metadata@^0.8.0",
      "aurelia-path": "github:aurelia/path@^0.9.0",
      "aurelia-route-recognizer": "github:aurelia/route-recognizer@^0.7.0",
      "aurelia-router": "github:aurelia/router@^0.12.0",
      "aurelia-task-queue": "github:aurelia/task-queue@^0.7.0",
      "aurelia-templating": "github:aurelia/templating@^0.15.0",
      "aurelia-templating-binding": "github:aurelia/templating-binding@^0.15.0",
      "aurelia-templating-resources": "github:aurelia/templating-resources@^0.15.0",
      "aurelia-templating-router": "github:aurelia/templating-router@^0.16.0",
      "bootstrap": "github:twbs/bootstrap@^3.3.4",
      "core-js": "npm:core-js@^0.9.4",
      "fetch": "github:github/fetch@^0.9.0",
      "font-awesome": "npm:font-awesome@^4.3.0",
      "paulvanbladel/aurelia-auth": "github:paulvanbladel/aurelia-auth@0.9.10"
    },
config.js:
    "paulvanbladel/aurelia-auth": "github:paulvanbladel/aurelia-auth@0.9.10",
    "github:paulvanbladel/aurelia-auth@0.9.10": {
      "aurelia-framework": "github:aurelia/framework@0.15.0",
      "aurelia-http-client": "github:aurelia/http-client@0.10.3",
      "aurelia-router": "github:aurelia/router@0.11.0"
    },

**Comment by lukeskinner** [comment]
I just setup a new aurelia site without any issues on 0.9.11 of aurelia-auth.

Can you check if you have any import statements like the one below? The {AuthorizeStep} may be different depending on what you're trying to import.
```
import {AuthorizeStep} from 'aurelia-auth';
```

If you do can you try changing them to this? 
```
import {AuthorizeStep} from 'paulvanbladel/aurelia-auth';
```

**Comment by paulvanbladel** [comment]
It will depend on how you install aurelia-auth.
Both or possible:
1. jspm install github:paulvanbladel/aurelia-auth
2. jspm install aurelia-auth.

in case of 1 (which you did I guess), you need import {AuthorizeStep} from 'paulvanbladel/aurelia-auth';
in case of 2: import {AuthorizeStep} from 'aurelia-auth';

Make sense?

**Comment by eaidland** [comment]
Just for testing I did the jspm install aurelia-auth.

![image](https://cloud.githubusercontent.com/assets/10772259/9733224/c4f77bf2-5629-11e5-980e-cc01514b0425.png)

**Comment by lukeskinner** [comment]
Example main.js file - at a guess you are missing the first import line as this gives me the same error without it.
```
import config from './authConfig';
import 'bootstrap';

export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
	.plugin('paulvanbladel/aurelia-auth', (baseConfig)=>{
         baseConfig.configure(config);
    })
    .developmentLogging();

  aurelia.start().then(a => a.setRoot());
}
```

Example authConfig.js file (from the installation instructions https://github.com/paulvanbladel/aurelia-auth)
```
var configForDevelopment = {
    providers: {
        google: {
            clientId: '239531826023-ibk10mb9p7ull54j55a61og5lvnjrff6.apps.googleusercontent.com'
        } 
        ,
        linkedin:{
            clientId:'778mif8zyqbei7'
        },
        facebook:{
            clientId:'1452782111708498'
        }
    }
};

var configForProduction = {
    providers: {
        google: {
            clientId: '239531826023-3ludu3934rmcra3oqscc1gid3l9o497i.apps.googleusercontent.com'
        } 
        ,
        linkedin:{
            clientId:'7561959vdub4x1'
        },
        facebook:{
            clientId:'1653908914832509'
        }

    }
};
var config ;
if (window.location.hostname==='localhost') {
    config = configForDevelopment;
}
else{
    config = configForProduction;
}


export default config;
```

You may have already seen it but there is a demo app using aurelia-auth here https://github.com/paulvanbladel/aurelia-auth-sample/tree/master/client.

**Comment by paulvanbladel** [comment]
I just updated the aurelia-auth-sample with the latest aurelia framework.
Anyhow the sample work fine with the latest aurelia-auth plugin, so you are probably doing something different...

**Comment by eaidland** [comment]
![image](https://cloud.githubusercontent.com/assets/10772259/9733947/ba75d592-562f-11e5-851f-3de14f61be3e.png)

I've done some more changes. Looks like it's up and running. Just the import 'bootstrap/css/bootstrap.css!'; that's not working.

**Comment by paulvanbladel** [comment]
Yeah, that's what I updated 2 minutes ago.
Please check aurelia-auth-sample, you will see that the css is now loaded differently, it's a breaking change in aurelia framework september release.

**Comment by eaidland** [comment]
Ok thanks. Got the New skeleton up and running.
Can't understand why the old one always download old refs even though I've removed them from both config and package

**Comment by eaidland** [comment]
That's the Aurelia packages not auth..

**Comment by eaidland** [comment]
Found out it was the "aurelia-validation" plugin. 

You can Close this case.

Thanks :D
