### ISSUE TITLE
getMe() doesn't send Authorization headers

### ISSUE THREAD

**Issue by theRemix** [paulvanbladel/aurelia-auth#24]
how do i use the auth.getMe() method to send the token in the Authorization headers?
 
![no Authorization Header](http://i.imgur.com/BpGsib6.png)
_it's 404 because i didn't bother creating the route yet before i figure out how to identify the user_

here's my authConfig.js

```
const DEV_CONFIG = {
  loginRedirect: '/#/',
  profileUrl : '/api/oauth/me',
  providers : {
    github : {
      url : '/api/oauth/github',
      clientId : 'xxxxxxxxxxxxxxxxxxxxxx',
      redirectUri: '/api/oauth/cb'
    }
  }
};
```

if i can get the token being sent in the Authorization header, then i can change `'profileUrl' : 'https://api.github.com/user' `

**Comment by paulvanbladel** [comment]
Not sure what you are doing different, but in https://github.com/paulvanbladel/aurelia-auth-sample everyting works as expected.
When calling getMe I see:
![image](https://cloud.githubusercontent.com/assets/4886272/9979904/3cf2abc8-5f84-11e5-97d9-6adf0c54b71c.png)

Does your app.js looks as follows:
```javascript
export class App {

  constructor(router, httpClientConfig, appRouterConfig){
    this.router = router;
    this.httpClientConfig = httpClientConfig;
    this.appRouterConfig = appRouterConfig;
  }
  
  activate(){
    
    this.httpClientConfig.configure();
    this.appRouterConfig.configure();
  }
}
```

**Comment by theRemix** [comment]
i added the constructor and activate steps, how do i inject httpClientConfig and appRouterConfig ?

```
Unhandled promise rejection TypeError: Cannot read property 'configure' of undefined
```

**Comment by paulvanbladel** [comment]
https://github.com/paulvanbladel/aurelia-auth-sample/blob/master/client/src/app.js

**Comment by theRemix** [comment]
yes i was missing the `httpClientConfig.configure()` step. everything works beautifully, thanks!
