### ISSUE TITLE
404 POST after popup window closes

### ISSUE THREAD

**Issue by devscott** [paulvanbladel/aurelia-auth#28]
I am getting a 404 after a successfull authentication. The following appears in the console after the authentication popup window closes on the aurelia-auth-sample project

```javascript
POST http://localhost:9000/ 404 (Not Found)processRequest @ aurelia-http-client.js:275f @ shim.min.js:1415(anonymous function) @ shim.min.js:1423b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
aurelia-http-client.js:275 XHR finished loading: POST "http://localhost:9000/".processRequest @ aurelia-http-client.js:275f @ shim.min.js:1415(anonymous function) @ shim.min.js:1423b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
oAuth2.js:105 error :undefined
shim.min.js:1444 Unhandled promise rejection HttpResponseMessage {requestMessage: HttpRequestMessage, statusCode: 404, response: "Cannot POST /↵", isSuccess: false, statusText: "Not Found"…}(anonymous function) @ shim.min.js:1444b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
shim.min.js:1444 Unhandled promise rejection HttpResponseMessage {requestMessage: HttpRequestMessage, statusCode: 404, response: "Cannot POST /↵", isSuccess: false, statusText: "Not Found"…}(anonymous function) @ shim.min.js:1444b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
shim.min.js:1444 Unhandled promise rejection HttpResponseMessage {requestMessage: HttpRequestMessage, statusCode: 404, response: "Cannot POST /↵", isSuccess: false, statusText: "Not Found"…}(anonymous function) @ shim.min.js:1444b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
```

authConfig.js
```javascript
var config = {
    //our Aurelia App Address
    baseUrl: 'http://localhost:9000/',
    loginUrl:'sessions/create',
    loginRedirect: '#/profile',
    logoutRedirect: '/',
    loginRoute: 'login',
    signupUrl: 'signup',
    profileUrl: '#/profile',
    tokenName: 'id_token',
    providers: {
        localIdentity: {
            clientId: 'javascriptClients',
            authorizationEndpoint: 'https://localhost:44300/core/connect/authorize/',
            redirectUri: 'http://localhost:9000/',
            scope: ['openid','profile', 'email'],
            scopePrefix: '',
            scopeDelimiter: ' ',
            requiredUrlParams: ['scope','nonce'],
            type: '2.0',
            responseType : 'id_token',
            display: 'popup',
            nonce: function() {
                var val = Math.random();
                return encodeURIComponent(val);
            },
            popupOptions: { width: 1020, height: 618 }
        }
    }
}
````

**Comment by paulvanbladel** [comment]
Hi,
Difficult to help remotely due to all dependencies (keys, custom provider).
I would suggest to put break point in exchangeForToken method and get the exchangefortokenurl and try to browse manually to that.

**Comment by devscott** [comment]
Thanks, I'll start looking there. 

A follow up question if I may, Is there anyway to not open up in a popup?  I don't see a configuration value for this and even if I comment out display and popupOptions, I still get a popup.

**Comment by paulvanbladel** [comment]
There is also a login method next to the authencate method

**Comment by paulvanbladel** [comment]
Scott,
May i ask which backend you are using?

**Comment by devscott** [comment]
I am using [IdentityServer3](https://github.com/IdentityServer/IdentityServer3). 

I think the problem is I'm trying to do OpenID instead of OAuth or OAuth2. Correct me if i am wrong but It looks like aurelia-auth currently supports OpenID? If true, is there any plans to support it in the near future?

**Comment by paulvanbladel** [comment]
Cool.
It is supported , google is openId connect and that works like charm.
Maybe try once this and debug through the code and read also the google spec.. by doing so the right insight will popup.

**Comment by paulvanbladel** [comment]
The config of google mentions openid
Check baseconfig.js

**Comment by devscott** [comment]
Sorry for the delay in response. I wanted to do my homework first and make sure that I am not wasting your time. 

I took a closer look at the google provider config within the baseConfig, as well as the google provider config from the Satellizer project. Everything is as it should be here, which isn't a suprise. I have always been able to authenticate and constent to the different scopes. The problem occurs after I consent.

After I consent, the popup tries to do a redirect, and exchangeForToken gets called. You previously mentioned that I should check to see if the changeForTokenURL is navigatible. It is, the url is the same as the base url.

In trying to figure out where it goes wrong from here I put a break point in the authTokenHandling helper within the app.httpClient.config and isAuthetnicated() is returning false. Within isAuthetnicated()  token is null. putting a breakpoint in setToken, I find that it is never called. 

which takes me back to this line from exchangeForToken

```Javascript
return this.http.createRequest(exchangeForTokenUrl)
		.asPost()
		.withContent(data)
		.withCredentials(this.config.withCredentials)
		.send()
		.then(function (response) {
                            
			return response;
                        
		})['catch'](function (err) {
                            
			console.log("error :" + err.content.message);
                            
			throw err;
                        
		});

/* with values being
exchangeForTokenUrl = 'http://localhost:9000/'
data = {code: undefined, clientId: "jsClients", redirectUri: "http://localhost:9000/"}
this.config.withCredentials = true   
userData = {}
*/
```

So I am looking for pointers on where to investigate next?

**Comment by paulvanbladel** [comment]
Hi scott,
So if i understand correctly, no valid response is received from your backend when the post request is sent. It looks strange to me the url is just the base url, there should be url part in the config.
Can you debug your backend?
Arent there any examples of the combi satellizer identityserver?

**Comment by devscott** [comment]
I used the [implicit javascript client example](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/JavaScriptImplicitClient) from identityServer and things work without a hitch. Now this is using [their own open id Connect client](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/JavaScriptImplicitClient/oidc.js) to make the calls. Seeing it worked there is what made me question if you supported open id connect.

**Comment by paulvanbladel** [comment]
The flows i am using in aurelia-auth-sample are the explicit ones. Look into the server map.

**Comment by paulvanbladel** [comment]
See
https://github.com/sahat/satellizer/wiki/Login-with-OAuth-2.0

**Comment by devscott** [comment]
Thanks. I will try that out and let you know.

**Comment by paulvanbladel** [comment]
This is the best 
https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2

**Comment by Vidarls** [comment]
I might be getting a little late to the game here but: @devscott were you able to get aurelia-auth working with an identityserver 3 backend?

**Comment by devscott** [comment]
@Vidarls Yes and No. [I forked the aurelia-auth project](https://github.com/devscott/aurelia-auth) and made some changes. Using the Hybrid flow, I was able to get things to work. I have an example of everything here. [Identity Server Examples](https://github.com/devscott/identityServer3Example). But this fork is not ideal. It is more of a collection of hacks to get things working.

The people over at thinktecture have an example OpenID JS Client doing Implicit flow. There is a branch within my fork where I am slowly bringing Thinktecture's client into  aurelia-auth the proper way, but could use some help.  I'll submit a pull-request once I am done and @paulvanbladel can do with it what he wants.

**Comment by Vidarls** [comment]
actually, I think it would be better not to use the full oidc client of thinktecture as it re-implements a lot of stuff already available in aurelia. Stuff like http client and promises. Adding the full oidc client / manager seems to add a quite a bit of extra code to dl for the client (bad for mobile clients in particular).

As I see it, there is not that much missing from the current aurelia-auth implementation:

So far it looks to me like the main thing missing is support for `id_token` (as supposed to just token), as well as the combination `id_token token` (both profile and access token).

The flow in the oauth2 client is hardcoded to use implicit flow (no code exchange) if the provider is set up to ask for just `token` anythin else seems to trigger some sort of `authorization code` flow. (which according to the security wizards I've read the blogs of is a bad idea, as JS clients should not be trusted enough to handle authorization codes).

I tried to do a homebrew approach based on the simple js sample of thinktecture, but I stranded on the popup-polling stuff that seems to have som intricacies to it (particularly when mobile clients are involved.)

I'm currently hacking a bit on the aurelia-auth plugin to see if I can get something working well enough with the implicit flow and both id_token and access token.

**Comment by devscott** [comment]
I agree it does re-implement a lot of things that Aurelia already does.  I have been substituting the Aurelia bits, certainly we would want to lean on Aurelia everywhere possible.

In my investigations, the major parts that are missing form aurelia-auth to do implicit flow are using the discovery endpoint and validating the tokens once we get them. 

I have not worked with the popup on mobile yet, but I did find one issue with the pop up polling where Aurelia-auth is treating a user closing the popup as an error. This isn't correct, because the end session point, depending on how it is configured, will display a confirmation that the user has been successfully logged out.

**Comment by Vidarls** [comment]
using the discovery endpoint would be valid for more than just the hybrid flow right? (also a very good idea, makes config much less verbose).

For validating the tokens, we could actually cheat, and just have the identityserver validate them for us using the validation endpoint. (saves some crypto js, and might be lighter on less capable devices)

**Comment by Vidarls** [comment]
Would a sane apporach in the beginning be to add an explicit oidc provider (adding an extra file to oAuth1 and oAuth2.js) so we don't initially interfer with any existing deployments? And then later @paulvanbladel could (if he wanted) pull in the bits that may be useful for the existing providers?

**Comment by devscott** [comment]
Yeah that is exactly what I am doing [here](https://github.com/devscott/aurelia-auth/blob/OpenIDConnect/src/OpenIDConnect.js).

**Comment by Vidarls** [comment]
I got something working with two very simple alterations now:

in config of `auelia-auth` I set response type like this:

`responseType : 'id_token%20token',` 

and I altered the `oAuth2.js` just directly in the jspm dl folder like this:

```js
//if (self.defaults.responseType === 'token') {
if (self.defaults.responseType === 'id_token%20token') {
                                return oauthData;
}
``` 

To force implicit flow.

I have not checked on decoding token accessing claims and such, but at least I got authenticated :smile: 

Not sure on how to proceed the best way. I'm not entirely comfortable just pulling in https://github.com/IdentityModel/oidc-client, as it brings a lot of baggage in the form of duplication and client side crypto, and also it provides it own http client thingy. Ideally something more lightweight would be better IMO.

But it looks like you're working on reducing the duplication, and also utilizing the aurelia http client for internal requests in the plugin. Then only the heavy(?) crypto stuff remains. If this is only for validating the token, can we just use the token validation of identityserver? Or at least add a config option to only load and use client side stuff if we want?

Anyway, overdue for a weekend now. Let me know if you want more hands on this.

**Comment by Vidarls** [comment]
It will in any case be better to have a single codebase with some configurability than having two competing solutions (or even worse, to have many different ones in private repos...)

**Comment by devscott** [comment]
@Vidarls yes I agree one code base is ideal and is something I am hoping for. Hopefully will hear from @paulvanbladel

**Comment by paulvanbladel** [comment]
Sure, if you want to add the implicit flow... go on.
Looking forward to the result.

**Comment by paulvanbladel** [comment]
Isn't implicit flow not covered already by:
... in oauth2.js
if (self.defaults.responseType === 'token') {
                    return oauthData;
                }

**Comment by Vidarls** [comment]
yeah, but it does not handle id_token and the combination of id_token and token (both access token and profile info)

**Comment by Vidarls** [comment]
Also, as @devscott mentions, the tokens are not validated against the signature. Also, it would be nice to include an option to use the well known discovery doc of oauth.

**Comment by paulvanbladel** [comment]
I see. I have currently no time to dive into this, but i am confident in you guys.
Happe to merge a PR on this.
Would it make sense that i reorganize a bit aurelia-auth-sample, which has currently only a nodejs sample? I could create subfolders for each backend: plain asp.net web api, identityserver, ....
Please advise on that.
Thanks.

**Comment by Vidarls** [comment]
I've spent some time looking at @devscott 's emerging solution, and I believe that refining his work and incorporating an oidc provider (in addtion to oAuth 1 and 2) is the best approach. Possibly pulling in his validation of tokens into the other two providers as well.

Main difference from pure oAuth and oidc seems to be supporting the separate id_token to gain access to profile claims from it. (My band-aid hack above simply ignores the id_token, and uses the profile endpoint to get profile data.) This should be implemented in the authService class, (companion method to `getTokenPayload`). 

 Regarding the sample project:

I would be happy to provide a pr with an IdentityServer based .net backend to demonstrate the oidc capabilities of aurelia-auth. I don't believe there's any need for different hosting samples there, as this is well documented and explained in the Identityserver documentation and sample repository. Just a very simple api and the IdentityServer should suffice imo.

**Comment by RWOverdijk** [comment]
@Vidarls Considering how this has been solved in a PR, which has been merged, can this be closed?

**Comment by Vidarls** [comment]
Not really, my PR was a dirty hack just to allow the an id_token to exist without crashing the app. I believe the work @devscott is doing should be considered the final solution to this as it will be a more comprehensive, secure and proper implementation.

**Comment by RWOverdijk** [comment]
@Vidarls Thank you for bringing me up to speed. To make sure I understand, is @devscott still on this?

**Comment by devscott** [comment]
@RWOverdijk This issue can probably be closed. We can create a new issue for adding support for an OpenIDConnect client. 

Currently my availability is limited so any PR are greatly appreciated or if someone else is wanting to run with this, I would be more than happy to sit down them and discuss where things are at.

**Comment by RWOverdijk** [comment]
@devscott Cheers. I'll close this one and create a new one. Thanks!
