### ISSUE TITLE
I think getPayload should be moved from utility Authentication class to main interface

### ISSUE THREAD

**Issue by digizen** [paulvanbladel/aurelia-auth#29]
In my opinion, any non-trivial use-case for JWT authentication likely involves pulling data out of the token by the client. This can involve the specific permissions granted in the application, the username, the first name, or whatever else the server chooses to store in the token. 

There's already a function that extracts the data, Authentication.getPayload(). I think this should be moved into the declared interface as the heavier cousin of "isAuthenticated()". 

What do you think?

**Comment by paulvanbladel** [comment]
Sure, very good point.
Do you mind creating a PR?
Thanks a lot .

**Comment by digizen** [comment]
Will do.

**Comment by paulvanbladel** [comment]
new version created v0.9.17
