### ISSUE TITLE
Add plugin to aurelia-registry

### ISSUE THREAD

**Issue by PWKad** [paulvanbladel/aurelia-auth#3]
Aurelia is starting a universal registry of plugins for now - this contains a list of plugins and will be used by the CLI soon to install the plugins automatically for the developer.  

https://github.com/aurelia/registry/blob/master/plugin-registry.json

**Comment by paulvanbladel** [comment]
Nice. I will pick that up after my holiday.

**Comment by kristianmandrup** [comment]
You can also add it to the jspm registry directly ;)

https://github.com/jspm/registry/blob/master/registry.json

But I guess, better to use the aurelia plugin registry...

**Comment by PWKad** [comment]
Definitely recommend adding to jspm also - jspm will help other users get the latest version of your app very easily - with the aurelia registry we are simply hoping to create a single source of all things Aurelia no matter where / how they are served to help gain exposure for these various plugins.

Thanks!

**Comment by paulvanbladel** [comment]
@PWKad  : what is your view on #7 ?
