### ISSUE TITLE
Login, token JWT

### ISSUE THREAD

**Issue by eaidland** [paulvanbladel/aurelia-auth#31]
Hi!

Didn't know where to write the question...so it ended up in issues...sorry :)

I need to have the grant_type: 'password', in the request. Did not know how to use the standard you've created.

So how should it be done?

This is working for me at the moment, but doesn't feel correct...
```

	login(){
		var loginData = {
            grant_type: 'password',
            username: this.username,
            password: this.password
        };




		 return this.http.post(this.authService.config.baseUrl + this.authService.config.loginUrl, $.param(loginData))
			.then(response => {
		        //console.log('Got authentication response ' + response.content.access_token);
		        // console.log(this.authService);
		        
		        if(this.authService.config.storage==='localStorage'){
		        	localStorage.setItem(this.authService.config.tokenPrefix ? this.authService.config.tokenPrefix + '_' + this.authService.config.tokenName : this.authService.config.tokenName,response.content.access_token);
		        }else{
		        	sessionStorage.setItem(this.authService.config.tokenPrefix ? this.authService.config.tokenPrefix + '_' + this.authService.config.tokenName : this.authService.config.tokenName,response.content.access_token);
		        }


		 		if (this.authService.config.loginRedirect) {
		          window.location.href = this.authService.config.loginRedirect;
		        } else {	
		          window.location.href = window.encodeURI('/#welcome');
		        }
		     
				return response;
		     
		    }, error => {
		        this.error = 'Login Failed';
		    });

	};
```

**Comment by paulvanbladel** [comment]
The login method accepts an object as first param.
My feeling is that you can just do:
auth.login(loginData), where loginData is your object with the grant_type.

**Comment by eaidland** [comment]
With your standard:
```
{grant_type: "password", username: "myuser", password: "mypass"}
grant_type: "password"
password: "mypass"
username: "myuser"
```
{"error":"unsupported_grant_type"}


With my custom:
```
grant_type:password
username:myuser
password:mypass
```
Ok..


Your version is sent as request payload... mine as Form data...

What's missing?

**Comment by MikeGraf** [comment]
@eaidland - take a look at this ticket:https://github.com/paulvanbladel/aurelia-auth/issues/23

You need to serialize the object. We just used $.param() to do so - before sending it into the login method.

**Comment by eaidland** [comment]
Perfect!

Now it's just the redirect that isn't working.

In my custom login i had to 


		 		if (this.authService.config.loginRedirect) {
		          window.location.href = this.authService.config.loginRedirect;
		        } else {
		          window.location.href = window.encodeURI('/#welcome');
		        }

**Comment by eaidland** [comment]
Sorry... my bad... It's working now :+1: 

Thanks
