### ISSUE TITLE
Please update for latest aurelia release

### ISSUE THREAD

**Issue by wichert** [paulvanbladel/aurelia-auth#34]
Currently installing aurelia-auth pulls in versions of `aurelia-framework` and `aurelia-router` that are outdated.

**Comment by praga** [comment]
+1

**Comment by paulvanbladel** [comment]
Sure, I'll update later today :)

**Comment by paulvanbladel** [comment]
Done.

**Comment by wichert** [comment]
If I look at https://github.com/paulvanbladel/aurelia-auth/commits/v0.9.18 it looks like the v0.9.18 tag is missing the relevant changeset. In fact git tells me both tags reference the same changeset:

```
* 3920460 (HEAD -> master, origin/master, origin/HEAD) line up with latest framework release
* 38bf470 (tag: v0.9.18, tag: v0.9.17) new release for exposign getPayload method
```

**Comment by paulvanbladel** [comment]
i'm terribly sorry. My Bad. Sloppy mood today :)
I created now v0.9.19
