### ISSUE TITLE
Custom Config for http-client

### ISSUE THREAD

**Issue by schuetta92** [paulvanbladel/aurelia-auth#35]
Just wondering if there is a way to configure the http client to add  "x.withInterceptor(new ResponseInterceptor())" for it so I get handle any response errors globally instead of handling them on each call. 

I didn't find anything that allowed for customization, wondering if I just am missing it, and if not, if you have any plans to build it in?

**Comment by paulvanbladel** [comment]
Hi Ashly,
I don't think we need to open up the internals of aurelia-auth to achieve that.
Can you please verify the following sample which is basically injecting the httpClient in the app.js and then setup the interceptor on the httpClient class. Classes in aurelia are by default singletons, so the setup which is done by aurelia-auth for the processing of the JWT token does not interfere with your response interceptor. At least, that how I did understand it :)
Thanks for trying out following code.
Cheers.

```javascript
import 'bootstrap';
import {inject} from 'aurelia-framework';
import {Router} from 'aurelia-router';
import AppRouterConfig from 'app.router.config';
import HttpClientConfig from 'aurelia-auth/app.httpClient.config';
import {HttpClient} from 'aurelia-http-client';
@inject(Router,HttpClientConfig,AppRouterConfig,HttpClient )
export class App {

  constructor(router, httpClientConfig, appRouterConfig, http){
    this.router = router;
    this.httpClientConfig = httpClientConfig;
    this.appRouterConfig = appRouterConfig;
    this.http = http;
  }
  
  activate(){
    
    this.httpClientConfig.configure();
    this.appRouterConfig.configure();

  	this.http.configure(x => {
	    x.withInterceptor(new ResponseInterceptor());
  });
  }
}


class ResponseInterceptor {
  response(message) {
    console.log("we are manipulating the response here");
    return message;
  }

  responseError(error) {
    throw error; // or return an HttpResponseMessage to recover from the error
  }
}
```

**Comment by schuetta92** [comment]
Hey Paul, 

So after a little bit of debugging I got it working. Something that is pretty obvious but took me a bit to figure out is that my version of the http-client that I am using has to be the same version of the one you are using or it doesn't work. 

Thanks for the help!
