### ISSUE TITLE
Integration with Breezejs

### ISSUE THREAD

**Issue by WisdomCorp** [paulvanbladel/aurelia-auth#36]
Can you provide some guidelines how to integrate it with breezejs and asp.net webapi on server-side.

Example -  if I take aurelia-nwind-breeze example (by Jeremy Danyow) how we can integrate this plugin with it.

**Comment by paulvanbladel** [comment]
I don't think there is a touch point with BreezeJS (which is a great lib).
I have not example for asp.net web api, but what you need is very similar to the NodeJs example I provided : https://github.com/paulvanbladel/aurelia-auth-sample.
