### ISSUE TITLE
Typescript Definition File is not included

### ISSUE THREAD

**Issue by gregoryagu** [paulvanbladel/aurelia-auth#37]
I am trying to get Aurelia-auth working in a TS project. 

In the app file, I am trying to get this line converted to something that will work in TS:

    import HttpClientConfig from 'aurelia-auth/app.httpClient.config';

I created `aurelia-auth.d.ts` and put this code in it:

     declare module 'aurelia-auth' {
     export class HttpClientConfig {
        configure():any;
        }
    }

Then I try to import it:

    import {HttpClientConfig} from 'aurelia-auth';

This works as far as the compiler is concerned, but it doesn't actually inject it at runtime.

**Comment by paulvanbladel** [comment]
Can you make a PR for this?
Thanks.

**Comment by gregoryagu** [comment]
Well, I gave it my best shot, but being fresh off the c# banana boat, it's over my head.  I tried taking the source and converting it over to ts, but there are too many things I don't yet understand about both TS and js to make it work.  I will give this some more thought and if I come up with anything useful, I will let you know.

**Comment by paulvanbladel** [comment]
Thanks for giving it a try :)

**Comment by alfkonee** [comment]
Started Working on a d.ts file for this library with #76 . Currently most of the types are `any` but still improving it for better intellisense support
Also working on improving the gulp tasks to enable releasing with the d.ts file

**Comment by Vidarls** [comment]
Any chance of doing a release including the d.ts file? @paulvanbladel

**Comment by paulvanbladel** [comment]
Sure, I'll do asap when I'm in the code.

**Comment by alfkonee** [comment]
#87

**Comment by paulvanbladel** [comment]
done.
