### ISSUE TITLE
TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by geimbar** [paulvanbladel/aurelia-auth#39]
If for some reason exchangeForToken fails then it is possible that err.content is undefined:

.catch(err => {
                    console.log("error :" + err.content.message);
                    throw err;
                });

Please remove the catch block in 
https://github.com/paulvanbladel/aurelia-auth/blob/master/src/oAuth2.js

best regards, Arni Reginsson

**Comment by paulvanbladel** [comment]
Hi, 
Good catch :)
Updated in  v0.10.4
