### ISSUE TITLE
getPayload raise "Failed to execute 'atob' on Window: The string to be decoded is not correctly encoded."

### ISSUE THREAD

**Issue by hlj** [paulvanbladel/aurelia-auth#42]
I found when getPayload was called with special token string that include more than one '-'  or '/', it raise an exception: Failed to execute 'atob' on Window: The string to be decoded is not correctly encoded.
Example:
   the encoded text of Chinese  '贾翼' is '6LS-57-8'. 

Maybe there is a bug at this line:
https://github.com/paulvanbladel/aurelia-auth/blob/master/src/authentication.js#L42
It's only replace the first  '-' or '/' character in whole string.

**Comment by paulvanbladel** [comment]
Can you submit a pull request please?
thx

**Comment by hlj** [comment]
I already submitted a pull request, had any problem?

**Comment by paulvanbladel** [comment]
yeah, my apologies for the delay.

**Comment by hlj** [comment]
no matter. thx
