### ISSUE TITLE
Aurelia Pre-Beta Release (11-10-2015) causes aurelia-auth to break

### ISSUE THREAD

**Issue by nathanchase** [paulvanbladel/aurelia-auth#45]
It looks like this breaking change from the Aurelia pre-beta is causing an error in aurelia-auth:

*Router Pipeline steps now receive the NavigationInstruction instead of the NavigationContext. Pipeline steps should use instruction.getAllInstructions() and instruction.getAllPreviousInstructions() instead of context.nextInstructions and context.currentInstructions, respectively, to inspect current and previous instructions.* - from http://blog.durandal.io/2015/11/10/aurelia-pre-beta-release/

Looks like the AuthorizeStep class needs to be updated accordingly, at minimum. https://github.com/paulvanbladel/aurelia-auth/blob/master/dist/es6/authorizeStep.js

**Comment by paulvanbladel** [comment]
--> v0.11.0

**Comment by nathanchase** [comment]
Thank you!
