### ISSUE TITLE
baseUrl setting of HttpClient gets overwritten.

### ISSUE THREAD

**Issue by vbauerster** [paulvanbladel/aurelia-auth#59]
When HttpClient is configured by the user, like the following code, aurelia-auth plugin overwrites baseUrl setting, if its configure method gets called after. The only way to prevent default baseUrl setting to be overwritten, is to make sure that HttpClient's configure method gets called last.
```js
import {HttpClient} from 'aurelia-fetch-client';

@inject(HttpClient)
export class MyClass {

    constructor(http) {
        http.configure(config => {
            config.withBaseUrl('someBaseUrl/');
        });

        this.http = http;
    }

}
```
Also aurelia-auth plugin doesn't respect any user defined settings in HttpClient, it simply overwrites them all. It would be nice to respect user defined settings of HttpClient.
Possibly, [this quick idea](https://gist.github.com/vbauerster/85386cfc0396a7b56bee) will give you a light of what I mean.

**Comment by RWOverdijk** [comment]
@vbauerster Thank you for explaining what your problem is.

To be fair, the configure method supplied by aurelia-auth is optional. You could implement it yourself.

Could you tell me why the current approach is wrong?

**Comment by vbauerster** [comment]
Oh, I didn't know that it is optional. Well I didn't tell it is wrong, just as a user of a plugin I didn't expect that my HttpConfig settings will be overwritten, and to figure out why I had to spent some time in debugger. The good approach is to respect settings (like baseUrl and headers) in global HttpClient if they were applied and use them in plugin's config. Maybe it worth to remove baseUrl setting from plugin's config, as it actually duplicates HttpConfig's setting. Another idea - plugin's configure method could take a callback function, for explicit programmatic configuration by user.

**Comment by RWOverdijk** [comment]
I see. Well, if you can provide a PR that's BC and does what you want it to do, I'm interested! :)

**Comment by commercial-hippie** [comment]
I'm currently working around it like this:

``` js
this.fetchConfig.configure();
this.fetchConfig.httpClient.baseUrl = 'http://local.myurl.com.au/api/';	
```

**Comment by RWOverdijk** [comment]
That's, odd. Can't you set it in configure? Like so: https://github.com/SpoonX/aurelia-api#configuring-the-client

I know it's a different module, but it essentially does the same thing.

**Comment by RWOverdijk** [comment]
I have some news on this. I found an issue in [fetch-client](https://github.com/aurelia/fetch-client/pull/31). Every time you call configure, it overwrites the baseUrl. It's unfortunate, but the case. A fix can be made for this.

**Comment by RWOverdijk** [comment]
Closing this and moving to https://github.com/SpoonX/aurelia-auth
