### ISSUE TITLE
How can I call my web api controller method from the login with a post request.

### ISSUE THREAD

**Issue by SivaJonnala** [paulvanbladel/aurelia-auth#60]
I have controller method to check for the user credentials. I want to call this method with aurelia login. But I don't want to give the username and password from the header. I want access as a post method.
How can pass the username and password via filters from the JS webservice call in the login method.

**Comment by RWOverdijk** [comment]
No idea what you're saying buddy. The login method already does a post

**Comment by SivaJonnala** [comment]
Yeah I know its post method but with this login How can I hit my webservice ? How it will look into the Webservice Url which I have given in my baseConfig file to the "loingUrl" property.

**Comment by RWOverdijk** [comment]
So you want to configure the url it should talk to?

**Comment by SivaJonnala** [comment]
The url shold talk to sql server database table in my system. Using the repository I have written in my buissiness layer.

**Comment by SivaJonnala** [comment]
My context is how can I access the baseConfig file containing in my app i.e., src/auth/baseCofig.js

**Comment by RWOverdijk** [comment]
@SivaJonnala Perhaps we can talk about this over at gitter, I'm having a hard time understanding you due to the language barrier.

**Comment by SivaJonnala** [comment]
Ok no problem @RWOverdijk

**Comment by RWOverdijk** [comment]
After talking on gitter, I at least know this isn't an issue, but a question. Questions go on stackoverflow, or gitter :) I'm close this and handling this with you on gitter.
