### ISSUE TITLE
after installing : jspm install aurelia-auth i get in chrome dev tool: http://localhost:4000/dist/nav-bar.html.js 404 (Not Found) 

### ISSUE THREAD

**Issue by estrica2000** [paulvanbladel/aurelia-auth#61]
after installing : jspm install aurelia-auth i get in chrome dev tool: http://localhost:4000/dist/nav-bar.html.js 404 (Not Found) , and i have no idea why suddently this error, it was working before installing the plugin. Tried to uninstall but the error pesrsists, any idea where i should look for to fix this?

the instalation looked like this: 
jspm install aurelia-auth
     Updating registry cache...
     Looking up github:paulvanbladel/aurelia-auth
     Looking up npm:aurelia-fetch-client
     Looking up npm:aurelia-framework
     Looking up npm:aurelia-http-client
     Looking up npm:aurelia-router
     Looking up npm:core-js
     Looking up npm:aurelia-pal
     Looking up npm:aurelia-path
     Looking up npm:aurelia-binding
     Looking up npm:aurelia-dependency-injection
     Looking up npm:aurelia-loader
     Looking up npm:aurelia-logging
     Looking up npm:aurelia-metadata
     Looking up npm:aurelia-task-queue
     Looking up npm:aurelia-templating
     Looking up npm:aurelia-event-aggregator
     Looking up npm:aurelia-history
     Looking up npm:aurelia-route-recognizer

warn Using local override for npm:core-js@1.2.6
     Looking up github:systemjs/plugin-json
     Looking up github:jspm/nodelibs-fs
     Looking up github:jspm/nodelibs-path
     Looking up github:jspm/nodelibs-process
     Looking up npm:path-browserify
     Looking up npm:process
     Looking up github:jspm/nodelibs-assert
     Looking up npm:assert
     Looking up npm:util
     Looking up npm:inherits
     Looking up github:jspm/nodelibs-util
ok   Up to date - aurelia-auth as github:paulvanbladel/aurelia-auth@^0.11.4 (0.11.4)
     Installed Forks

                     npm:aurelia-binding 1.0.0-beta.1.0.1 1.0.0-beta.1.0.2
                  npm:aurelia-task-queue 1.0.0-beta.1 1.0.0-beta.1.0.1
                  npm:aurelia-templating 1.0.0-beta.1 1.0.0-beta.1.0.1

**Comment by RWOverdijk** [comment]
@estrica2000 Could you try again?

**Comment by estrica2000** [comment]
thank you! seems working now. What has been changed, or what was the problem for my own clarification ? thanks

**Comment by RWOverdijk** [comment]
@estrica2000 jspm. You had installed forks because of a difference of dependencies.

**Comment by estrica2000** [comment]
thank you

**Comment by estrica2000** [comment]
for some reason i thought the error had gone but n,  it's still there.  Basically i have this https://github.com/paulvanbladel/aurelia-loopback-sample

As soon has i do: jspm install aurelia-auth i get the eror on the title: http://localhost:4000/dist/nav-bar.html.js 404 (Not Found)

**Comment by RWOverdijk** [comment]
@estrica2000 Probably the same reason. The dependencies are outdated.

**Comment by RWOverdijk** [comment]
@estrica2000 Just tried, it works fine for me. Basically, when there are jspm forks, you have to straighten them out. Either a dep, or your project have outdated / different dependencies (versions).

You can check for forks by running `jspm inspect --forks`

**Comment by estrica2000** [comment]
i don't know enough to understand everything you said! anyway did you try in https://github.com/paulvanbladel/aurelia-loopback-sample ?
i will test it again the original version of aurelia-loopback-sample again now, anway, i just did this as you said and i get: jspm inspect --forks
     Installed Forks

                     npm:aurelia-binding 1.0.0-beta.1.0.1 1.0.0-beta.1.0.2
                  npm:aurelia-task-queue 1.0.0-beta.1 1.0.0-beta.1.0.1
                  npm:aurelia-templating 1.0.0-beta.1 1.0.0-beta.1.0.1.

**Comment by estrica2000** [comment]
what is "straighten them out." in this case?

**Comment by RWOverdijk** [comment]
@estrica2000 I did, and it works fine for me.

In your config.js, look up what's using the versions spat out by jspm inspect, and figure out what has to be updated.

For further questions please ask on gitter.

**Comment by estrica2000** [comment]
alright RWOverdijk
