### ISSUE TITLE
manual build creates different  code

### ISSUE THREAD

**Issue by doktordirk** [paulvanbladel/aurelia-auth#65]
i'm having trouble building a copy of aurelia-auth. 
after running npm install, jspm install, gulp build, the files in dist/system differ and the pugin fails (orignial plugin works fine)

eg in dist/system/baseConfig.js line 12-14 ib the original repo is
```
  setters: [function (_authUtils) {
      authUtils = _authUtils['default'];
    }],
```
changed to
```
 setters: [function (_authUtils) {
      authUtils = _authUtils.authUtils;
    }],
```
any ideas what i might do wrong?

**Comment by RWOverdijk** [comment]
I'm not sure, not. I'm currently not capable of having a look, but I'll check this out as soon as I can. If that takes too long, I hope you'll be able to find it yourself :)

**Comment by doktordirk** [comment]
i found the problem in parts. my jspm, babel ,or whatever version don't do default imports as specified

*fails*
import  authUtils  from './authUtils';

*works*
import { default as authUtils } from './authUtils';

you have a quick idea why, tell me please. else this issue can be closed i guess

**Comment by doktordirk** [comment]
found the problem. you don't import default exports properly. 

you use 
import {authUtils} from './authUtils';
which is a named import of authUtils

you meant
import authUtils from './authUtils';
short for the named import of default as
import {default as authUtils} from './authUtils';

another default export is app.httpClient.config.js where as  app.fetchClient.config.js is named. so issue (https://github.com/paulvanbladel/aurelia-auth/issues/37) could be related. as well as the problem some others had with the example project issue (https://github.com/paulvanbladel/aurelia-auth-sample/issues/10)

**Comment by RWOverdijk** [comment]
@doktordirk I made the mistake of accepting someone's "CS formatting" PR without thoroughly reviewing it.

**Comment by doktordirk** [comment]
did cost me some time, but now i have my fist pull request merged. tx.  jippy!! ;)

**Comment by RWOverdijk** [comment]
You should join gitter :)
