### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by gotokatsuya** [paulvanbladel/aurelia-auth#69]
Thank you for publishing awesome library.

Does it support electron ?

It mays not to work well..

**Comment by RWOverdijk** [comment]
@gotokatsuya Yes and no. It does work, but on login and logout you get redirected causing errors. I've created an issue for it [over at my fork](https://github.com/SpoonX/aurelia-auth/issues/2). I might backport it to this repo seeing how it's being used a lot.

**Comment by gotokatsuya** [comment]
@RWOverdijk Thank you
