### ISSUE TITLE
token not provided - bad request

### ISSUE THREAD

**Issue by robertogonzalezdelarosa** [paulvanbladel/aurelia-auth#70]
my app is working just fine but after some time the token is not sent with headers  which results in a bad request. Token exists in Local Storage

**Comment by RWOverdijk** [comment]
@robertogonzalezdelarosa Did you configure the fetch client?

**Comment by robertogonzalezdelarosa** [comment]
I'm using http client and works as expected, requests are made and server returns data successfully but after some time (around 30 min or an hour) token is not included in the following requests but token is visible in Local Storage. This is where http client is configured : 

@inject(Router, HttpClientConfig, AppRouterConfig)

export class App {

  constructor(router, httpClientConfig, appRouterConfig) {
    
    this.router = router;

    // Client configuration provided by the aureliauth plugin
    this.httpClientConfig = httpClientConfig;

    // The application's configuration, including the
    // route definitions that we've declared in router-config.js
    this.appRouterConfig = appRouterConfig;
  };
  
  activate() {
    
    // Here we run the configuration when the app loads
    this.httpClientConfig.configure();
    this.appRouterConfig.configure();

  };
}

**Comment by RWOverdijk** [comment]
Are you using refresh tokens? :)

**Comment by robertogonzalezdelarosa** [comment]
Hooo!!! you are totally right. Thank you very much!.

**Comment by RWOverdijk** [comment]
No problem. That's a missing feature... I'm going to implement it on [my fork](https://github.com/SpoonX/aurelia-auth). I've stopped development on this repo because of the amount of changes I have planned.

**Comment by robertogonzalezdelarosa** [comment]
hello again. I was trying to add token refresh to aurelia auth plugin but there are some things that I don't understand one of them is why isAuthenticated() method is inside some sort of loop. 
Can you please put me in right direction?

**Comment by alfkonee** [comment]
@robertogonzalezdelarosa Join this (gitter)[https://gitter.im/SpoonX/Dev]  we're currently working on  the refresh token implementation
