### ISSUE TITLE
Pass authConfig directly to plugin call (remove function declaration)

### ISSUE THREAD

**Issue by AdamWillden** [paulvanbladel/aurelia-auth#71]
Could the aurelia-auth code take the configuration directly as follows:
```javascript
import authConfig from './authConfig';
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-auth', authConfig);

  aurelia.start().then(() => aurelia.setRoot());
}
```

Rather than the function we have to pass in at the moment?
```javascript
import authConfig from './authConfig';
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-auth', (baseConfig) => {
         baseConfig.configure(authConfig);
    });
  aurelia.start().then(a => a.setRoot());
}
```

Or does what I'm proposing already work?

**Comment by RWOverdijk** [comment]
@AdamWillden It could, and I can see why you'd want that. I'll ad it to my roadmap. If you wish to submit a PR, that's appreciated, too.

**Comment by AdamWillden** [comment]
@RWOverdijk I looked into the source code to make a PR where should I push it (here or your SpoonX fork)? What's the general idea here? You're a collaborator for this project yet working on a refactored version. I'm intrigued!

**Comment by RWOverdijk** [comment]
@AdamWillden I have some bigger plans for this module, so I forked it. I'm a collaborator on this repository so it won't die before paul finds time to maintain it again :)

**Comment by RWOverdijk** [comment]
As to where you should submit the PR to, I'd prefer the SpoonX one, but either will do. :)

**Comment by AdamWillden** [comment]
@RWOverdijk Okay thanks. I think bigger plans for this module are a good idea :+1:  I see your issue for a refresh token.

**Comment by AdamWillden** [comment]
@RWOverdijk Sorry to keep pinging you. The change would be really simple so I'll do a PR. Do you want to retain support for passing a function or would completely changing it be okay? What's you preferred method to check for a function `if (typeof param === 'function')`?

Personally I'd make it a breaking change and accept people will need to make a small modification when they update - but it's not my repo!

**Comment by AdamWillden** [comment]
Nevermind - I'm a doofus. it already checks if it's a function.

**Comment by RWOverdijk** [comment]
@AdamWillden I've added you to our channel on gitter. I think that's a faster way to communicate.
