### ISSUE TITLE
Question: Is the fetch client actually being used by the Auth Service or is the integration only so that we can use it?

### ISSUE THREAD

**Issue by alexduan** [paulvanbladel/aurelia-auth#75]
Sorry for the really dumb question, but I'm trying to configure everything with the fetch client, but looking at the code for AuthService, the requests made by aurelia-auth are all done using the http client. How does aurelia-auth know that you want to use fetch?

**Comment by RWOverdijk** [comment]
@alexduan It doesn't. It's one of the things I fixed [in my fork](https://github.com/SpoonX/aurelia-orm). However, if you wish to use this repository in stead, you can submit a PR. I can merge it for you. :)

**Comment by alexduan** [comment]
@RWOverdijk Thanks, I'll take a look. I think I also misunderstood what type of integration he was talking about. Looking more closely, I guess the integration is if I use the fetch client to make API requests, it will automatically inject the token from storage if auth is authenticated. The actual login and authentication process is still using the http client.

Clearly I have not had enough coffee today...

**Comment by RWOverdijk** [comment]
@alexduan You're absolutely right. I personally didn't like having another dep for that.

I'll consider this answered for now, if you wish to submit a PR you can reference this issue.

Thanks! :)

**Comment by DiknT** [comment]
Can this issue please be reopened for more clarification? From the readme I get the opinion that injecting and configuring the http client is optional and fetch would be used by default. Apparently this is not implemented in this repo yet, currently there is not Auth-header send when using fetch. What's the status on this? Thank you.

**Comment by paulvanbladel** [comment]
Yeah, a breaking change and simply giving up aurelia http client in favor of fetch client would be the best.
Feel free to submit PR.

**Comment by RWOverdijk** [comment]
@DiknT Could you specify what wasn't clear? Because I think I was pretty clear. This repo uses HttpClient, and mine doesn't. I also said we'd accept a PR on this one, so I'm curious what isn't clear (so I can clarify it for the next visitor of this issue).

**Comment by DiknT** [comment]
There are inconsistencies between the readme and the actual implementation which makes it difficult for newcomers to use this plugin out of the box before reading closed issues first and eventually switching to your fork.
There obviously was some confusion about the state of this repo the other day... I guess, I just wanted to hear Paul on this issue and his plan for this/his repo.
I don't mind closing this again then. Thanks a lot.

**Comment by RWOverdijk** [comment]
@DiknT I understand. The misunderstanding was my mistake. To clarify then: you're right. There are some inconsistencies. I actively develop [on my fork](https://github.com/SpoonX/aurelia-orm), and I'm still maintaining the repo. I do accept and comment on pull requests until Paul finds the time to continue development on this repository.

I hope this clarifies things, happy coding!
