### ISSUE TITLE
Exception thrown when token is invalid

### ISSUE THREAD

**Issue by jsobell** [paulvanbladel/aurelia-auth#77]
A corrupted token in local storage is causing an 'Unexpected token' exception when parsed in authentication.js as the decoded value is invalid JSON:

```
 var base64Url = token.split('.')[1];
            var base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
            var exp = JSON.parse(window.atob(base64)).exp;
```

This causes isAuthenticated() to fail rather than returning false.
All JSON.parse statements should probably have try catch.

**Comment by RWOverdijk** [comment]
@jsobell Two questions:

1. How did the corrupt token get stored in the first place?
2. I just [pushed a fix](https://github.com/SpoonX/aurelia-auth/pull/19) for this on my fork. Could you test it?

**Comment by jsobell** [comment]
@RWOverdijk ,

1. In my case I deliberately corrupted it as a test of someone attempting to hack it.
 My main concern is that if it becomes corrupt for any reason it is impossible to access the rest of the client app, as the aurelia-auth interceptor fails with an unhandled promise exception

2. Looks like someone beat me to it.

**Comment by RWOverdijk** [comment]
@jsobell 
1. When encoding it fails, it won't be set. But you're right, that's why I built the fix.
2. Yeah :) So does it work?

**Comment by paulvanbladel** [comment]
fixed.
