### ISSUE TITLE
Future Support for Refresh Tokens

### ISSUE THREAD

**Issue by alfkonee** [paulvanbladel/aurelia-auth#78]
Is there any plan to support JWT refresh tokens in the future??

**Comment by RWOverdijk** [comment]
@alfkonee It's [on the roadmap](https://github.com/SpoonX/aurelia-auth/issues/1) for our fork. If the changes we made don't conflict with this repository, we'll backport them. Also, help is welcome :) You can join us on [gitter](https://gitter.im/SpoonX/Dev) if you're interested.
