### ISSUE TITLE
switching between providers can cause authentication failure

### ISSUE THREAD

**Issue by timbell** [paulvanbladel/aurelia-auth#79]
I get a failure if I issue calls in this sequence:

1. authService.authenticate("live", true) => OK
2. authService.authenticate("google", true) => OK
3. authService.authenticate("live", true) => KO

The problem, I think, is that the OAuth2 "defaults" member is not reinitialized when calling "open" so in my case a scopePrefix of "openid" left behind by the "google" call is used for "live" which causes it to fail.

I checked in the satellizer sources and an OAuth1/OAuth2 instance is created for each authenticate call so the call to open gets fresh "defaults". The OAuth1/OAuth2 instances are being reused in aurelia-auth. Maybe move the "defaults" initialization to the top of "open" in OAuth1 and OAuth2 ?

**Comment by doktordirk** [comment]
There a PR for it in the spoonx repo

**Comment by paulvanbladel** [comment]
Cool. Thanks a lot. I'll take a look.

**Comment by doktordirk** [comment]
I.ll make a PR later





On Mon, Feb 8, 2016 at 12:21 AM -0800, "paul van bladel" <notifications@github.com> wrote:





Cool. Thanks a lot. I'll take a look.


---
