### ISSUE TITLE
Open id connect: Response mode "Post" issue

### ISSUE THREAD

**Issue by shivajiraot** [paulvanbladel/aurelia-auth#83]
@paulvanbladel @RWOverdijk @devscott @Vidarls 
Our Open Id connect server by default seems to be posting the data to redirect url. Fiddler shows that data is being posted to the url which it can not accept. error message: 'Cannot POST /'
Any way to get around this? the server supports other response modes too when specified in query. Which one should we use?

```
this.auth.authenticate('company', false, null)
            .then((response: any) => {
                console.log("Success" + response);
            },
            (error:any) => {
                console.log("Failed response " + error);
            });
```
Config:
```
providers = {
        company: {
            name: 'company',
            clientId: 'ourguid',
            authorizationEndpoint: 'https://login.microsoftonline.com/someid/oauth2/authorize',
            redirectUri: this.currentHost(),
            scope: ['profile'],
            scopePrefix: 'openid',
            scopeDelimiter: ' ',
            requiredUrlParams: ['scope', 'nonce', 'state'],
            optionalUrlParams: ['display'],
            responseType: 'id_token',
            state: '#/home',
            type: '2.0',
            nonce: this.getNonce(),
            popupOptions: { width: 1020, height: 618 },
            display: 'popup',
        }
    }

    getNonce() {
        return encodeURIComponent(
            ((Date.now() + Math.random()) * Math.random())
                .toString()
                .replace(".", "")
        );
    }

    currentHost() {
        return window.location.origin || `${window.location.protocol}//${window.location.host}`;
    }
```

**Comment by Vidarls** [comment]
I think this depends on what flow is defined for the provider. If you're trying anything with code exchange it may trigger some post action. I don't know the flows protocol by heart, but if you're tying to use openid connect, you need to specify `responceType: "id_token%20token" to get both access token and id_token. Also you should be using implicit flow or hybrid flow if I recall correctly.

**Comment by Vidarls** [comment]
See https://github.com/paulvanbladel/aurelia-auth/issues/28#issuecomment-152566938 where myself and @devscott were discussing similar issue

**Comment by paulvanbladel** [comment]
Yeah, bot aurelia-auth and the "mother lib" satellizer are confusing about if it's about oauth or openId connect.
Unfortunately I have few time the following period, but my plan would be to make a kind of reference implementation towards IdentityServer and use OpenIdConnect because for simple authentication that's the preferred way to do so. Read: http://leastprivilege.com/2016/01/17/which-openid-connectoauth-2-o-flow-is-the-right-one/ 
My feeling is that if things work agains IdentityServer we are on the right track, because I believe IdentityServer is currently *the* reference STS.
