### ISSUE TITLE
Customize parameter name for login method

### ISSUE THREAD

**Issue by stephenhuey** [paulvanbladel/aurelia-auth#84]
I'm enjoying aurelia-auth and I have a suggestion.  You have a long list of configurable items, e.g. tokenName, loginRoute, etc.  I see that the login method hardcodes the parameter name to email, and I'm wondering if you could make this configurable as well, e.g. in case my server is looking for  "username" instead.  Thanks!

**Comment by RWOverdijk** [comment]
@stephenhuey You already can. Simply pass in an object in stead of a string :)

**Comment by stephenhuey** [comment]
Ah, thanks!
