### ISSUE TITLE
login route: /login (authorizeStep.js:38) while trying to login

### ISSUE THREAD

**Issue by Slyfest** [paulvanbladel/aurelia-auth#85]
I have the following problem with aurelia-auth, here is common login snippet that i use:
```javascript
login() {
        return this.authService.login(this.email, this.password)
        .then(response => {
            console.log("Login response" + JSON.stringify(response));
        })
        .catch(err => {
            this.loginError = err.response;
        });
    };
```
When i'm trying to login, i see desirable console output, but also there is a message "login route : /login" from authorizeStep.js:38
which states that i am actually not authenticated

**Comment by paulvanbladel** [comment]
Can you check what happens on your server, because when it says you are not authenticated, it might mean that server side things are not as expected.
Try also https://github.com/paulvanbladel/aurelia-auth-sample.
