### ISSUE TITLE
Discuss: Project Conversion to Typescript 

### ISSUE THREAD

**Issue by alfkonee** [paulvanbladel/aurelia-auth#86]
@paulvanbladel Would it be possible to convert this project into Typescript since most of the code is in ES6 I think you should explore this

**Comment by paulvanbladel** [comment]
Great suggestion. Feel free also to submit PR. Thanks

**Comment by alfkonee** [comment]
Ok Will Submit a PR soon

**Comment by alfkonee** [comment]
@paulvanbladel I'm creating the TS port and I'm having some issues with the the deferred object in popup.ts event listener function
I'd like to know if this is a JS object or it's from a third party implementation of Promises I'm not too familiar with Promises Just yet haven't really taken a critical look at it please help
