### ISSUE TITLE
Login in latest release not working

### ISSUE THREAD

**Issue by vamp** [paulvanbladel/aurelia-auth#89]
```login('someStringForPayload')``` not working correctly, just because this string will be sent to server using json.

(required Content-Type - is "application/x-www-form-urlencoded; charset=UTF-8", desired - json)

**Comment by paulvanbladel** [comment]
Are you referring to the resource owner flow.
The lib and the sample (aurelia-auth-sample) are about the authorization code flow.
Are you using a specific server implementation?

**Comment by RWOverdijk** [comment]
@vamp Can the server be changed? The cors way (default) nowadays is json.

**Comment by vamp** [comment]
@paulvanbladel, @RWOverdijk 
I'm following the [oauth2 guideline](http://oauth.net/2/) and know, and using .net lib on server-side (so from my side everything is ok and version v0.11.7 works fine for me

**Comment by RWOverdijk** [comment]
@vamp So 0.11.7 sends it as `application/x-www-form-urlencoded; charset=UTF-8`?

**Comment by mikhailshilkov** [comment]
Yes, same problem for me. The server expects the request parameters to be form encoded, and they used to be form encoded in 0.11.7, but not the body is actually json. Need a way to override it, at least.

**Comment by RWOverdijk** [comment]
I think I know which PR caused that. https://github.com/paulvanbladel/aurelia-auth/pull/80/files by @DiknT 

The point there, is to use fetch-client in stead of HttpClient. The way it was tagged (with clear BC break) is wrong @paulvanbladel 

It can be configured I think, might be in the docs: https://gist.github.com/bryanrsmith/14caed2015b9c54e70c3#configuration

**Comment by mikhailshilkov** [comment]
Yes, the PR is correct, `body: json(content)` is causing the issue

**Comment by RWOverdijk** [comment]
Do you have the same issue with [this repo](https://github.com/SpoonX/aurelia-auth)? If so, we can provide a fix for it (configured).

**Comment by mikhailshilkov** [comment]
I haven't see this repo before... What's the reason of this fork? I'm ok with original 0.11.7 version for now.

**Comment by paulvanbladel** [comment]
Would changing from: 
body: json(content) ===> body: content
not simply solve the problem?

**Comment by RWOverdijk** [comment]
@paulvanbladel I suppose it could, that's why I asked @mikhailshilkov to test our fork :) It has all (most of) this stuff taken care of already.

**Comment by mikhailshilkov** [comment]
@RWOverdijk No, that repo doesn't seem to work either. If I provide login/password pair, it will send json. If I provide an object, it will send json again.

**Comment by paulvanbladel** [comment]
@vamp can you point to the paragraph number in oauth spec you are referring to.
http://tools.ietf.org/html/rfc6749
Thanks a lot.

**Comment by vamp** [comment]
@paulvanbladel, simply:
```body: typeof(content)==='string' ? content : json(content)```

and content-type for token request (and sample) was described in:
https://tools.ietf.org/html/rfc6749#section-4.3.2

**Comment by mikhailshilkov** [comment]
@vamp This won't work. If you pass a request as string, the condition `(typeof arguments[1] !== 'string')` will be false, so content will be made out of login + password. I would change the condition then to check if password is `undefined`.
But even better, the content type should be configurable in plugin config.

**Comment by paulvanbladel** [comment]
@mikhailshilkov  the check if the argument is not string is on the SECOND param, so in case of a call to the login method as follows will work, under the assumption we specify also the content type:
var creds = "grant_type=password&email=" + this.email + "&password=" + this.password;

        return this.auth.login(creds)
		.then(response=>{
			console.log("success logged " + response);
		})
		.catch(err=>{
			console.log("login failure");
		});

**Comment by mikhailshilkov** [comment]
@paulvanbladel Ah, ok, my bad

**Comment by paulvanbladel** [comment]
No worries @mikhailshilkov :)

**Comment by paulvanbladel** [comment]
ok, fixed in 0.11.10.
No need for extra config, we presume that when the only param is a string, the password grant type is used and we add the relevant content-type and of course do  not json encode.
@vamp @mikhailshilkov  thanks for taking the latest release and check if it works as expected.
Cheers
