### ISSUE TITLE
Redirect back to initial page after the successful login

### ISSUE THREAD

**Issue by mikhailshilkov** [paulvanbladel/aurelia-auth#90]
**Change request to support this kind of scenario:**

1. User opens a bookmarked page, e.g. http://mysite.me/#/users
2. She gets redirected to http://mysite.me/#/login
3. After the successful login she is redirected back to http://mysite.me/#/users but not to the default page http://mysite.me/#/welcome

**Comment by paulvanbladel** [comment]
Yeah, that would be a great feature.
Feel free to make a PR.
