### ISSUE TITLE
authentication.js returns true if token contains more or less than 3 periods

### ISSUE THREAD

**Issue by TomSelleck** [paulvanbladel/aurelia-auth#91]
In authentication.js, when verifying the token, it has:

```
     // There is a token, but in a different format. Return true.
     if (token.split('.').length !== 3) {
        return true;
      }
```

How does this make sense? I could understand:

```
     // There is a token, but in a different format. Return true.
     if (token.split('.').length !== 3) {
        return false;
      }
```

Is this a mistake? How can we say a token is valid by having the incorrect number of "." ?

**Comment by paulvanbladel** [comment]
No it's not a mistake, it's by design :)

In the context of the implicit flow, access tokens don't have always 3 parts.
See: https://github.com/sahat/satellizer/pull/592

cheers
paul.
