### ISSUE TITLE
Accessing the response after login failure

### ISSUE THREAD

**Issue by mattdwen** [paulvanbladel/aurelia-auth#96]
I'd like to be able to read the message returned from the server when a login call fails. Right now it only appears to be possible to read the `response.statusText` when catching login errors.

The server I'm programming against returns different reasons for the login failure as plain body text, e.g.

```
HTTP/1.1 401 Unauthorized
Content-Type: text/plain; charset=utf-8
Server: Kestrel
X-SourceFiles: =?UTF-8?B?QzpcUHJvamVjdHNcZGl2YTNcc3JjXERJVkEuRnVzaW9uXHNyY1xESVZBLkZ1c2lvblx3d3dyb290XGFwaVxhdXRoXHNpZ25pbg==?=
X-Powered-By: ASP.NET
Date: Thu, 18 Feb 2016 02:53:36 GMT
Content-Length: 53

Sorry, you entered an incorrect username or password.
```

I can't see any way the response is exposed after the promise is rejected.

I've had a play around in **authService.js**, and modified the `status(response)` method to reject the promise with the actual `response` object, as follows:

```
function status(response) {
    if (response.status >= 200 && response.status < 300) {
      return Promise.resolve(response);
    } else {
      //return Promise.reject(new Error(response.statusText));
      return Promise.reject(response);
    }
  }
```

This then allows me to handle the response in the catch, and extract what I need.

Is there an existing way to access the response on failure that I've missed?
Or is this worth considering as a PR?

Thanks!

**Comment by paulvanbladel** [comment]
Thanks for the feedback.
Make sense.  May I ask how do you get the actual error message in login.js ?

**Comment by paulvanbladel** [comment]
please try v0.12.8.

**Comment by mattdwen** [comment]
Works great, thanks!

I see you've edited your comment, but I'm getting the response text with

```
response.text().then(text => {
  if (text === '') {
    text = response.statusText;
  }
  console.log(text);
});
```

When I was messing with **authService.js**, I tried to resolve the text in there, but it wouldn't resolve for some reason.

**Comment by paulvanbladel** [comment]
thanks for the info, Indeed .text() works also. I used .json().
Take care Matt.
paul.
