### ISSUE TITLE
Error thrown from status

### ISSUE THREAD

**Issue by schuetta92** [paulvanbladel/aurelia-auth#97]
Is there a reason that the status function throws the the statusText from the response when it errors? 

Wouldn't it be better to throw the json from the response since the auth might have been rejected for different reasons?

**Comment by paulvanbladel** [comment]
I think that's updated in the latest bits.
Can you check it out please?
Thanks

**Comment by paulvanbladel** [comment]
Oops, you are right, StatusText is still returned :)
There was in the mean time PR for this.
Will be fixed soon Ashley.
Take care
paul.

**Comment by schuetta92** [comment]
I updated to 12.8 and that throws the whole response, but it looks like in master it is throwing response.statusText

**Comment by paulvanbladel** [comment]
yeah, I merged too quickly the PR.
Is 12.8 doing what i should do for you?

**Comment by schuetta92** [comment]
Yes, 12.8 has the behavior I would expect.
